GET https://api.odcloud.kr/api/15109950/v1/uddi:1f78fe49-78b4-4784-a5f0-e2c8a60515b4?page=1&perPage=10&serviceKey=dBNtx7RfjFv8vyqxm0cZEHs7PT7gljRBPMSh4IbIGHIqqm0pm2LHDWg1tscRjy0AIBspJ4CAJv5%2Fo%2BZaEoloxg%3D%3D